# Finds the EASYLOGGING library

IF( NOT EASYLOGGING_PACKAGE_DIR )
  MESSAGE( "ERROR: EASYLOGGING_PACKAGE_DIR requires to be set" )
ENDIF( NOT EASYLOGGING_PACKAGE_DIR )

SET( EASYLOGGING_INCLUDE_DIR "${EASYLOGGING_PACKAGE_DIR}/src" )
SET( EASYLOGGING_LIBRARY )

IF( EASYLOGGING_PACKAGE_DIR AND EASYLOGGING_INCLUDE_DIR )
  SET( EASYLOGGING_FOUND "YES" )
  MESSAGE( STATUS "Found EASYLOGGING!" )
ENDIF( EASYLOGGING_PACKAGE_DIR AND EASYLOGGING_INCLUDE_DIR )

