
INCLUDE( include_guard )
INCLUDE_GUARD()

IF( NOT DEFINED CANCELLAR_BUILD_SOURCE_DIR )
  SET( CANCELLAR_BUILD_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}" )
ENDIF()

IF( NOT DEFINED CANCELLAR_BUILD_BINARY_DIR )
  SET( CANCELLAR_BUILD_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}" )
ENDIF()

IF( NOT DEFINED CANCELLAR_BUILD_VENDOR_DIR )
  SET( CANCELLAR_BUILD_VENDOR_DIR "${CANCELLAR_BUILD_SOURCE_DIR}/vendor/" )
ENDIF()

## Common settings
ENABLE_TESTING()

# for vim youcompleteme
SET ( CMAKE_EXPORT_COMPILE_COMMANDS 1 )

## Common build configuration
INCLUDE( GroupInVisualStudio )
INCLUDE( BuildHelpers )
INCLUDE( CancellarConfig )
INCLUDE( CompilerConfig )
#INCLUDE( MagicAssets )