INCLUDE_GUARD()
INCLUDE( vendor-libs/vendor-helper )

ADD_SUBDIRECTORY( "${CANCELLAR_BUILD_VENDOR_DIR}/lua" )
# HACK! uses the build directory
TARGET_INCLUDE_DIRECTORIES(  liblua INTERFACE "${CANCELLAR_BUILD_VENDOR_DIR}/lua/src" "${CANCELLAR_BUILD_BINARY_DIR}/vendor/lua/" )
INTERNAL_PRESET_DEPENDENCY( liblua )