# Finds X11 includes and libraries

INCLUDE_GUARD()

FIND_PACKAGE( OpenGL REQUIRED )
LIST( APPEND CANCELLAR_VENDOR_INCLUDES "${OPENGL_INCLUDE_DIR}" )
LIST( APPEND CANCELLAR_VENDOR_LIBRARIES "${OPENGL_LIBRARIES}" )

