# Finds X11 includes and libraries

INCLUDE_GUARD()

IF( CANCELLAR_PLATFORM_LINUX )
  FIND_PACKAGE( OpenAL REQUIRED )
  LIST( APPEND CANCELLAR_VENDOR_INCLUDES "${OPENAL_INCLUDE_DIR}" )
  LIST( APPEND CANCELLAR_VENDOR_LIBRARIES "${OPENAL_LIBRARIES}" )
ENDIF()

