
INCLUDE_GUARD()
INCLUDE( vendor-libs/vendor-helper )

ADD_SUBDIRECTORY( "${CANCELLAR_BUILD_VENDOR_DIR}/ticpp" )

APPEND_VENDOR_INCLUDES( "${CANCELLAR_BUILD_VENDOR_DIR}/ticpp/" )
APPEND_VENDOR_LIBRARIES( ticpp )

